[package]
name = "panasonic2020"
version = "0.1.0"
authors = ["mosh <mosh21168@gmail.com>"]
edition = "2015"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
